FROM ptebic.azurecr.io/public/azureml/aifx/stable-ubuntu2004-cu116-py38-torch1120:latest

RUN python -m pip install azureml-core \
                          accelerate \
                          datasets \
                          transformers
