FROM mcr.microsoft.com/azureml/curated/pta-pytorch-1.11-py38-cuda11.5-gpu:6

RUN python -m pip install accelerate \
                          datasets \
                          optimum \
                          transformers
